Repository m2l-limayrac/Fredy, pull requests merged in 2018-03, with the labels that each got.

#3 ajout du isValidate dans pour la note de frais
  README.md
  sql/fredi_plot3_data.sql
  src/DAO/DemandeurDAO.php
  src/DAO/NoteDeFraisDAO.php
  src/controllers/DemandeurController.php
  src/models/Demandeur.php
  src/models/NoteDeFrais.php
  src/views/demandeur/details.php
Labels: feature

#12 correction du bug du code postal lors de l'insertion des adherent
  src/controllers/AdherentController.php
  src/controllers/DemandeurController.php
Labels: bug

#13 modification fichier SQL pour la validation
  sql/fredi_plot3_structure.sql
Labels: bug

#14 résolution du bug de typo
  src/controllers/DemandeurController.php
  src/views/demandeur/details.php
Labels: bug

#15 supression du create database dans le fichier data.sql
  sql/fredi_plot3_data.sql
Labels: bug

#16 résolution du bug d'affichage de l'id au lieu du nom dans le formulaire
  src/controllers/AdherentController.php
  src/controllers/DemandeurController.php
  src/views/adherent/ajout.php
  src/views/demandeur/register.php
Labels: bug

#17 Fix/database
  sql/fredi_plot3_data.sql
  sql/fredi_plot3_structure.sql
  src/DAO/AdherentDAO.php
  src/DAO/DemandeurDAO.php
  src/controllers/DemandeurController.php
  src/models/Adherent.php
  src/models/Demandeur.php
  src/views/adherent/ajout.php
  src/views/adherent/settings.php
  src/views/demandeur/register.php
Labels: bug, feature

#18 resolution + modification SQL
  API/lignes.php
  sql/fredi_plot3_structure.sql
  src/views/demandeur/details.php
Labels: bug, help wanted
